---
- hosts: localhost
  connection: local
  tasks:

    - name: Create containers
      community.general.lxd_container:
        name: '{{ item.name }}'
        ignore_volatile_options: true
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: '{{ item.image }}'
        profiles: ["default", "x11"]
        wait_for_ipv4_addresses: true
        timeout: 600
      loop:
        - { name: lab, image: debian/12 }
