---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:

  - name: Set git user in localhost
    community.general.git_config:
      name: user.name
      scope: global
      value: Leonardo Anjoletto Ferreira

  - name: Set git email in localhost
    community.general.git_config:
      name: user.email
      scope: global
      value: 43471239+anjoletto@users.noreply.github.com

  - name: Set neovim as default editor
    community.general.git_config:
      name: core.editor
      scope: global
      value: nvim

  - name: Create config folder
    file:
      path: ~/.config
      state: directory

  - name: Create GTK folder
    file:
      path: ~/.config/gtk
      state: directory

  - name: Clone pure (zsh) repo
    git:
      repo: https://github.com/sindresorhus/pure.git
      dest: ~/.config/pure

  - name: Clone dotfiles repo
    git:
      repo: https://github.com/anjoletto/dotfiles.git
      dest: ~/.dots/dotfiles

  - name: Create link for ZSH configuration
    file:
      src: ~/.dots/dotfiles/zsh/zshenv
      dest: ~/.zshenv
      state: link

  - name: Create links for configurations
    file:
      src: '~/.dots/dotfiles/{{ item  }}'
      dest: '~/.config/{{ item }}'
      state: link
    loop:
      - nvim
      - tmux.conf
      - bat
      - sxhkd
      - dunst
      - rofi
      - autorandr
      - alacritty.yml
      - qutebrowser

  - name: Create links for GTK configurations
    file:
      src: '~/.dots/gui-config/gtk'
      dest: '~/.config/{{ item }}'
      state: link
    loop:
      - gtk-2.0
      - gtk-3.0
      - gtk-4.0

  - name: Create link for Xresources configuration
    file:
      src: ~/.dots/gui-config/x11/xresources
      dest: ~/.Xresources
      state: link

  - name: Create link for Xinitrc configuration
    file:
      src: ~/.dots/gui-config/x11/xinitrc
      dest: ~/.xinitrc
      state: link

  - name: Create link for user-dirs configuration
    file:
      src: ~/.dots/gui-config/x11/user-dirs.dirs
      dest: ~/.config/user-dirs.dirs
      state: link
