---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:

  - name: Set git user in localhost
    community.general.git_config:
      name: user.name
      scope: global
      value: Leonardo Anjoletto Ferreira

  - name: Set git email in localhost
    community.general.git_config:
      name: user.email
      scope: global
      value: 43471239+anjoletto@users.noreply.github.com

  - name: Set neovim as default editor
    community.general.git_config:
      name: core.editor
      scope: global
      value: nvim

  - name: Clone TUI repo
    git:
      repo: git@github.com:anjoletto/tui-config.git
      dest: ~/.dots/tui-config

  - name: Create link for ZSH configuration
    file:
      src: ~/.dots/tui-config/zsh/zshenv
      dest: ~/.zshenv
      state: link

  - name: Create links for configurations
    file:
      src: '~/.dots/tui-config/{{ item  }}'
      dest: '~/.config/{{ item }}'
      state: link
    loop:
      - nvim
      - tmux.conf
      - bat
      - starship.toml

  - name: Clone pure (zsh) repo
    git:
      repo: https://github.com/sindresorhus/pure.git
      dest: ~/.config/pure

  - name: Clone GUI repo
    git:
      repo: git@github.com:anjoletto/gui-config.git
      dest: ~/.dots/gui-config

  - name: Create link for GUI configuration
    file:
      src: '~/.dots/gui-config/{{ item  }}'
      dest: '~/.config/{{ item }}'
      state: link
    loop:
      - alacritty.yml
      - qutebrowser
