---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:

  - name: Clone i3 repo
    git:
      repo: https://github.com/anjoletto/i3wm-config.git
      dest: ~/.dots/i3wm-config
    tags:
      - i3

  - name: Create link for i3 configuration
    file:
      src: ~/.dots/i3wm-config/{{ item }}
      dest: ~/.config/{{ item }}
      state: link
    loop:
      - i3
      - polybar
    tags:
      - i3

  - name: Clone qtile repo
    git:
      repo: https://github.com/anjoletto/i3wm-config.git
      dest: ~/.dots/qtile/
    tags:
      - qtile

  - name: Create link for qtile configuration
    file:
      src: ~/.dots/qtile
      dest: ~/.config/qtile
      state: link
    tags:
      - qtile
